name:                lottery
version:             0.1.0.0
github:              "tvestelind/lottery"
license:             BSD3
author:              "Tomas Vestelind"
maintainer:          "tomas.vestelind@gmail.com"
copyright:           "none"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            hobby-project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tvestelind/lottery#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - mtl
  - text
  - refined
  - QuickCheck
  - random
  - containers
  - extra

executables:
  lottery-cli:
    main: Main.hs
    source-dirs: app/cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lottery
    - optparse-applicative
    - random
    - refined
    - text

tests:
  lottery-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lottery
    - QuickCheck
    - hspec
    - refined
    - text
    - random
    - either-unwrap
